version: '3.7'
services:
  app:
    user: bun
    image: oven/bun:1.0.4
    restart: unless-stopped
    working_dir: /usr/src/app
    command: sh -c "bun install && bun run dev"
    ports:
      - '8080:5173'
    volumes:
      - ./:/usr/src/app
